nelmio_cors:
  defaults:
    allow_origin: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: []
    max_age: 3600
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    "^/": ~
